### ISSUE TITLE
Viewing Metadata of Collections: Information not assigned correctly

### ISSUE THREAD

**Issue by przell** [Open-EO/openeo-web-editor#101]
Hi Matthias, 
when I look at the metadata of collections in the Eurac web editor (logged in with Eurac credentials, https://editor.openeo.org/0.4/) the dimension values are not assigned correctly to the dimension names. The y values go into the band slot:
![webviewer_metadata](https://user-images.githubusercontent.com/51962348/86369852-47d17800-bc7f-11ea-8ba5-e87c53726660.jpg)
I don't know if its related to our data, to our implementation of the web editor or the web editor version or if its a general problem.
Best, 
Peter

**Comment by m-mohr** [comment]
Die Version 0.4 wird nicht mehr weiterentwickelt, aber spannend wäre es die neue Version zu prüfen. Welche Collection war das genau?

**Comment by przell** [comment]
> Die Version 0.4 wird nicht mehr weiterentwickelt, aber spannend wäre es die neue Version zu prüfen.

@aljacob can you check this? Do you have implemented it that far yet?

> Welche Collection war das genau?

I recognized it on this one:
LIA_Sentinel1_Track015
But after some random checks it seems to be true for all collections.

**Comment by m-mohr** [comment]
The Web Editor exactly shows what the Collection returns on the server. All seems correct.  See here: https://openeo.eurac.edu/collections/LIA_Sentinel1_Track015 The extent is actually in the spectral dimension, not in Y. So that needs to be solved server-side.

**Comment by przell** [comment]
Thanks for verifying!
Sorry for that. I thought this had been checked on our side :confounded:
