### ISSUE TITLE
Math operations: Sorting of input

### ISSUE THREAD

**Issue by przell** [Open-EO/openeo-web-editor#102]
Hi Matthias, 
im using math operations like subtract in reduce. The ordering of the input matters (e.g. 1-2 vs 2-1). I do not find a solution how to have the datacube input as the first value when subtracting a constant. 
When I drag the datacube to the input first i cannot add a constant
When I add the constant first and then drag the datacube it works, but i can't change the position of the two inputs (datacube is always second):
![webviewer_mathop1](https://user-images.githubusercontent.com/51962348/86372429-6dac4c00-bc82-11ea-8ff3-d445caff0d66.jpg)

![webviewer_mathop2](https://user-images.githubusercontent.com/51962348/86372411-671dd480-bc82-11ea-85d8-8cc40a9f559f.jpg)

All the best, 
Peter

**Comment by m-mohr** [comment]
There's something wrong, it should shown an array editor. Which back-end is it (URL)?

On the other hand, you can calculate with a datacube directly.

**Comment by przell** [comment]
It's Eurac backend on this webeditor URL: https://editor.openeo.org/0.4/
The problem is also true for other math processes but most important it is in subtract and divide.

> On the other hand, you can calculate with a datacube directly.
You mean outside of the reduce? I think it behaves in the same way.

**Comment by m-mohr** [comment]
I checked it. Indeed, the Web Editor in v0.4 doesn't support constructing math operations properly if "data types" are mixed (a reference to a parameter/node is a different data type then a number internally). That's described in issue #75 and has been fixed for v1.0. v0.4 is not developed any further thus I'm closing here, please migrate to 1.0.

**Comment by przell** [comment]
Thanks for checking. 

> please migrate to 0.5 (API 1.0)

We're on our way!
