### ISSUE TITLE
If process accepts datacube only as reject parameter

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-web-editor#103]
Sorry I should have put this in the web-editor issues.

Anyway, the if block accepts data from a node only for the reject parameter, but I think it should allow to connect a datacube also to the accept one.

> There is also the question if only constants are support or if also functions can be executed after evaluation (as in our usecase)

> You can simply pass a process result to accept/reject, but then you may run into the issue I described also in Open-EO/openeo-processes#162.
> 
> Edit: Sorry, for whatever reason I accidentally edited your post instead of replying.
> 

_Originally posted by @m-mohr in https://github.com/Open-EO/openeo-processes/issues/164#issuecomment-652439608_

**Comment by m-mohr** [comment]
*I transferred this issue.*

For me datacubes work for both accept and reject value. Thus I can't reproduce. Please always report the back-end used when reporting issues. What back-end are you using? It could also be a wrong process spec on the back-end side though.

**Comment by clausmichele** [comment]
I see, I was trying it on VITO  back-end, on GEE works as expected! I'll report in their repository.

**Comment by m-mohr** [comment]
Interestingly, for v1.0 it also works on VITO for me.

**Comment by clausmichele** [comment]
Well, now it works for me too...anyway, thanks for the support Matthias

**Comment by m-mohr** [comment]
Let me know when it comes up again, maybe it's an edge case we can then reproduce better.
