### ISSUE TITLE
Linux/Firefox: Buttons are too big

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-web-editor#104]
The buttons on Linux Firefox are too big, see 
![Firefox 78 (left) and Chromium 83 (right) on ubuntu 19.10](https://user-images.githubusercontent.com/8262166/87406554-23e82d80-c5c1-11ea-8b0b-521752056740.png)

This should be improved. Windows shows the intended (smaller) buttons on all browsers.

**Comment by m-mohr** [comment]
Some help from @soxofaan :

> I had a quick inspect and it seems firefox uses a 17px left-right border on buttons, on chromium it's only 2px
> 
> ![image](https://user-images.githubusercontent.com/8262166/87407507-8b52ad00-c5c2-11ea-8156-7d3f151c6ca7.png)

Setting border-width: 1px makes the borders ugly. I guess it will be hard then to fix this issue properly as I don't know how to set the default Firefox style but without those big "margins"

**Comment by m-mohr** [comment]
Firefox on Mac: 

![image](https://user-images.githubusercontent.com/8262166/87408705-28faac00-c5c4-11ea-9e50-ffe745afa6fa.png)

Safari on Mac is fine, too.

**Comment by m-mohr** [comment]
Some background: https://blog.jkip.de/uebergrosse-buttons-in-firefox-46/

**Comment by soxofaan** [comment]
from https://codepen.io/andybelldesign/pen/Vxpjvo:  adding `    -moz-appearance: none;` also helps

**Comment by m-mohr** [comment]
Issue has been resolved.
