### ISSUE TITLE
Make the jobs sub windows adjustable in size

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-web-editor#106]
In my opinion, there is lot of space wasted to visualize the part showing the jobs list. Is it possible to make it shrinkable? So that more space can be used for the block editor. It is already doable for the lateral panels but not for the lower one.
It would be helpful with big graphs!

![image](https://user-images.githubusercontent.com/31700619/88805481-7f184380-d1af-11ea-8d88-337fe778a26d.png)

**Comment by m-mohr** [comment]
Sure, I'll look into that. But there's also a full screen mode for the block editor in the upper right corner you may use until then.

**Comment by m-mohr** [comment]
![88805481-7f184380-d1af-11ea-8d88-337fe778a26d](https://user-images.githubusercontent.com/8262166/88809685-b4736000-d1b4-11ea-884a-e1f494726c98.png)

**Comment by m-mohr** [comment]
![IMG-20200729-WA0018](https://user-images.githubusercontent.com/8262166/88809832-d836a600-d1b4-11ea-8853-3aac5cac3041.jpg)

**Comment by clausmichele** [comment]
Yes I know about the fullscreen mode, but when you are building a graph from scratch it's not that useful since you can't add new blocks in fullscreen but only modify and connect the current ones.

**Comment by m-mohr** [comment]
Oh, you should be able to add blocks. If that doesn't work, it's a bug I have to fix.

**Comment by clausmichele** [comment]
This is what I see in fullscreen mode, I can't see any way to add new blocks except the insert formula.
![image](https://user-images.githubusercontent.com/31700619/88890740-57be8680-d242-11ea-8128-fabb4adf6c6c.png)

**Comment by m-mohr** [comment]
Yeah, indeed. I figured out that only works in "sub" process graphs yet. I'm fixing that now.

**Comment by m-mohr** [comment]
You can get the list of processes/collections in fullscreen mode now. That's a temporary workaround for now.
