### ISSUE TITLE
url parameter to prefill the client ID

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-web-editor#109]
when I go to https://editor.openeo.org/?server=https://openeo.vito.be/openeo/1.0  and want to log in with OIDC, I have to specify the client ID. 
It would be handy if this could be pre-filled from an URL parameter, allowing easy access from a bookmark (or other URL sharing mechanism)

**Comment by m-mohr** [comment]
That sounds like a good idea.

One thing to note is that there could be multiple providers (see EODC) and I can't tell which OIDC provider the client ID belongs to. So we'd need to set both the OIDC provider and client id for it to work.

**Comment by m-mohr** [comment]
Is maybe not so relevant anymore with the introduction of "default_clients" in the API.
