### ISSUE TITLE
unreadable error messag when OIDC client does not support implicit flow

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-web-editor#110]
I was experimenting with OIDC auth on VITO backend, and when the OIDC client does not support the implicit flow, the error message is unreadable:

![Screenshot from 2020-09-08 10-07-58](https://user-images.githubusercontent.com/44946/92450182-64c48300-f1bb-11ea-917a-faf5145e9f14.png)

**Comment by m-mohr** [comment]
How did you get this? I tried to connect to VITO and I was able to login.

**Comment by soxofaan** [comment]
It happened when the client I was using did not have the implicit flow enabled.
I enabled it then, so you can not really reproduce the issue anymore with the public client.

I created a new OIDC public client (see backend credentials doc) without implicit support so you should be able to reproduce.

**Comment by m-mohr** [comment]
This seems to be either an issue of KeyCloak or the OIDC library. I just get the error message as it is (with the "+") and I don't think I should guess how to encode random errors that are not human-readable.

**Comment by m-mohr** [comment]
Origin is Keycloak: https://github.com/keycloak/keycloak/blob/master/services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java#L290

Then it's passed via URL to the OIDC client, thus the + chars in the message (URL encoding). The OIDC client should probably handle that, but it doesn't. So it should be reported to them.

Nevertheless, I found a way to detect this case and the editor can handle it properly now.
