### ISSUE TITLE
Allow access to the workspace panel without authentication

### ISSUE THREAD

**Issue by Ardweaden** [Open-EO/openeo-web-editor#113]
Some openEO services don't support authentication yet (e.g. sentinel-hub). It would be great if web editor allowed processing data without authentication for such services.

Currently, line https://github.com/Open-EO/openeo-web-editor/blob/929c1b0050140df20c206d34f529b10a5c9991a3/src/components/IDE.vue#L25 hides the workspace panel if the user is not logged in.

**Comment by m-mohr** [comment]
It was supported earlier, but from 1.0.0 on I expect back-ends to implement at least the simple Basic authentication for processing.
The API doesn't allow me to really check whether processing features work without authentication and thus people may get confused if they use the discovery mode and see the processing UI, but can't do anything on other back-ends that require authentication. 
Thus I won't implement this option again, sorry.
