### ISSUE TITLE
How to connect AND process

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-web-editor#116]
I am not able to merge two boolean masks with the AND process. I tried both with reduce_dimensions -> array_element -> and, apply-> array_element -> and but in both cases the AND process wasn't accepting the given input.
I'm working with the Web Editor of VITO, which has implemented the AND process. I don't know if it's a problem of the editor or the back-end. 
Here is a screenshot 
![image](https://user-images.githubusercontent.com/31700619/94905245-d7fca480-049c-11eb-976e-0470a098a40f.png)

and the process graph generated:

```
{
  "process_graph": {
    "1": {
      "process_id": "load_collection",
      "arguments": {}
    },
    "2": {
      "process_id": "apply",
      "arguments": {
        "data": {
          "from_node": "1"
        },
        "process": {
          "process_graph": {
            "1": {
              "process_id": "array_element",
              "arguments": {
                "data": {
                  "from_parameter": "x"
                }
              }
            },
            "2": {
              "process_id": "array_element",
              "arguments": {
                "data": {
                  "from_parameter": "x"
                }
              }
            },
            "3": {
              "process_id": "and",
              "arguments": {
                "x": true,
                "y": true
              },
              "result": true
            }
          }
        }
      },
      "result": true
    }
  }
}
```

**Comment by m-mohr** [comment]
That sounds related to #114. I'll investigate today, thanks.

**Comment by m-mohr** [comment]
Has been fixed in dev, will publish it later.

**Comment by m-mohr** [comment]
Deployed.
