### ISSUE TITLE
"Plus" button doesn't work when in "Code" view

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-web-editor#117]
When working on a process graph in "Code" mode (i.e. while editing the JSON directly), clicking on the `+` button of a collection (that has been searched for in the sidebar) doesn't work. Instead, there's a "fatal error" saying:

> this.activeEditor().insertProcess is not a function

**Comment by christophfriedrich** [comment]
It's the same for processes, too

**Comment by m-mohr** [comment]
Fixed, but not deployed yet.

**Comment by m-mohr** [comment]
Has been released and deployed as version 0.5.0.
