### ISSUE TITLE
GEE web editor unable to edit reducer, returns error

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-web-editor#119]
Editing a process graph with GEE web editor returns an error when trying to edit the reducer part of processes like reduce_dimension or apply.
![image](https://user-images.githubusercontent.com/31700619/95847086-972e4680-0d4c-11eb-9069-358cefaaae2d.png)

P.s.: I don't know if this is related to the GEE back-end or to the web editor, please move this issue accordingly.

**Comment by m-mohr** [comment]
Likely a Web Editor issue that was introdoced here: https://github.com/Open-EO/openeo-web-editor/commit/5cdc0c683cbf7c3043ac2dc164967b9fe512adf5#diff-b1c48f1278ba5007dfbb9f77e71f47cfbdcdbe5f09e3d4d84bc82130d44e9b61R122

Sorry for the inconvenience, I'll fix it next week!

**Comment by m-mohr** [comment]
Thanks for reporting!
I fixed it, should be working now. Please let me know if there are still issues, @clausmichele.
