### ISSUE TITLE
loadCollection: band names

### ISSUE THREAD

**Issue by jonathom** [Open-EO/openeo-web-editor#125]
Since band names can be backend-specific (e.g. S2 "B8" vs "B08") or hard to keep in mind (e.g. S5Ps "tropospheric_NO2_column_number_density" - band), entering the correct names by hand when loading a collection could be assisted with some sort of overview or dropdown menu to choose the band names from.

**Comment by m-mohr** [comment]
Agreed, the parameter editor (especially for load_collection) should at least offer one of these features:
1. Open the HTML version of the collection, e.g. via an (i) button behind the select box (easy)
2. Provide the band names in a select box itself depending on the selected collection id (complex)

**Comment by m-mohr** [comment]
Both options have been implemented.

**Comment by jonathom** [comment]
Yes, both work. Perfect!
