### ISSUE TITLE
Datetime picker too large

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-web-editor#126]
The datetime picker is too large, it adds like half of the size to the bundle.

The related issue and PR were never merged:
https://github.com/chronotruck/vue-ctk-date-time-picker/pull/172
https://github.com/chronotruck/vue-ctk-date-time-picker/pull/164

An option could be to migrate to: https://element.eleme.io/#/en-US/component/datetime-picker#datetimepicker

**Comment by clausmichele** [comment]
Additionally, often I have to select the date twice to get a correct range, otherwise it reverts back to the current year and date with no selection. It's an annoying bug, especially when you have to select time spans in previous years

**Comment by m-mohr** [comment]
Yes, indeed. I've also seen this behavior and we'll try to get another solution in the next months.

**Comment by m-mohr** [comment]
Here's an alternative we could use: https://github.com/mengxiong10/vue2-datepicker
It seems to fulfill all requirements, although the temporal chooser is not very intuitive...

**Comment by m-mohr** [comment]
A new date/time picker has been implemented. How do you like it, @clausmichele ?

**Comment by clausmichele** [comment]
> 
> 
> A new date/time picker has been implemented. How do you like it, @clausmichele ?

Nice, finally it works without double selection! But the default view is a code block for no selection, is this intentional? 
![image](https://user-images.githubusercontent.com/31700619/120291312-7575d580-c2c3-11eb-9505-28f111c0bd19.png)

**Comment by m-mohr** [comment]
@clausmichele that was not the case for me, so is unintentional. Which process or collection is that?

**Comment by clausmichele** [comment]
It's load_collection on our Eurac back-end (all the collections) with the live web editor, version 0.7.2.

**Comment by m-mohr** [comment]
Hmm, I can't reproduce it. You just dragged and dropped load_collection into an empty model builder window and opened the options window? Which browser are you using?

**Comment by m-mohr** [comment]
Okay, it's only happening for ADO_CORINE_100m_3035 for me... It's happening because the temporal extent is `[null,null]`. Will check.

**Comment by clausmichele** [comment]
Yes I've also checked better now, it happens only if the collection has no temporal extent. Apart from this it works fine on all the other cases!

**Comment by m-mohr** [comment]
Should be fixed in version 0.7.3, have just deployed it.
