### ISSUE TITLE
`linear_scale_range` loads numbers as string into process graph

### ISSUE THREAD

**Issue by jonathom** [Open-EO/openeo-web-editor#139]
When applying a `linear_scale_range` and setting the min/max values in the web editor, they are added as strings to the process graph code, although numeric is required.

**Comment by m-mohr** [comment]
Which back-end is that?

**Comment by jonathom** [comment]
tested with earthengine and VITO so far.

**Comment by m-mohr** [comment]
Fixed and deployed (clear your cache and make sure the version is 0.7.0-beta.3).
