### ISSUE TITLE
Credential provider button text is chopped off

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-web-editor#141]
on VITO backend we currently provide 3 OIDC providers, 
combined with the "internal" and "no credentials" -> the button text is chopped off:

![Screenshot from 2021-04-28 15-23-49](https://user-images.githubusercontent.com/44946/116411729-45579480-a836-11eb-81e5-4d63a3c42e3a.png)

**Comment by m-mohr** [comment]
This is already fixed in oidc-default-client branch and just needs a new version of the vue-components to be released. :-)

**Comment by m-mohr** [comment]
Deployed as Web Editor 0.7.0-beta.5

**Comment by soxofaan** [comment]
confirmed, thanks
