### ISSUE TITLE
OIDC popup window is quite small for EGI Check-in 

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-web-editor#142]
When using auth code OIDC flow with EGI Check-in, the popup is quite small for the EGI Check-in pages:

![Screenshot from 2021-04-28 15-28-32](https://user-images.githubusercontent.com/44946/116414093-79cc5000-a838-11eb-8edf-f5008d519cc8.png)

**Comment by m-mohr** [comment]
Yes, that's the default and works for most IPs, but EGIs UI is pretty large so that's an issue. But you can easily make it larger, of course.

**Comment by m-mohr** [comment]
Next release will open in 750x550px instead of 500x500px.

**Comment by m-mohr** [comment]
Deployed.
