### ISSUE TITLE
Possibility to download JSON/CSV after synchronous jobs

### ISSUE THREAD

**Issue by jonathom** [Open-EO/openeo-web-editor#147]
As discussed, the possibility to not only view the result of such calculations in the web editor but to also download/view the respective text as 'pure' JSON / CSV would be greatly appreciated.

**Comment by m-mohr** [comment]
The download itself is a bug of the back-end: https://github.com/Open-EO/openeo-python-driver/issues/50

What I can do is to allow the "rendered" version (i.e. the HTML version of JSON) to optionally be shown also in a text editor (Code Mirror).

**Comment by m-mohr** [comment]
Implemented, will be available soon in v0.8.0.
