### ISSUE TITLE
Error importing D22 process graph

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-web-editor#150]
If I import the D22 process graph like this https://raw.githubusercontent.com/Open-EO/openeo-usecases/master/evi_d22_usecase/D35/jrc.json I get the following error:
![image](https://user-images.githubusercontent.com/31700619/122023710-15edee80-cdc8-11eb-970e-976db6162a5d.png)

**Comment by m-mohr** [comment]
Which back-end?

**Comment by m-mohr** [comment]
EURAC is missing the sum process.
