### ISSUE TITLE
Empty Lines trigger `NaN`, not changeable

### ISSUE THREAD

**Issue by jonathom** [Open-EO/openeo-web-editor#151]
![Screenshot from 2021-06-15 21-04-19](https://user-images.githubusercontent.com/45635480/122109143-53309b80-ce1d-11eb-9ece-3d3fb4457ba4.png)

When editing processes like `apply_kernel` (property `kernel`), adding and deleting a number in the value field leads to `NaN` being shown in the value field. It cannot be removed anymore, nor can any number be added.
The same applies for `apply_neighborhood` (property `size` as seen above), although only when setting type to `number`, and deleting the `0` displayed in the value field.
These are the processes for which I discovered this so far, there are probably more where numbers are added in arrays.

**Comment by m-mohr** [comment]
Thanks. Just to make sure, is it the VITO back-end?

**Comment by jonathom** [comment]
It is VITO backend, but I tested with EURAC (`apply_kernel`) as well and same result there.

**Comment by m-mohr** [comment]
I've deployed a hot-fix in v0.7.6, could you try whether it works for you? Haven't had a chance to do a lot of testing.
Make sure it's loading v0.7.6 and not an old version from the cache.

**Comment by jonathom** [comment]
Works for me :+1:, nice!
