### ISSUE TITLE
Error with basic auth?

### ISSUE THREAD

**Issue by mmacata** [Open-EO/openeo-web-editor#169]
After the merge of `Better OpenID Connect integration, incl. refresh token support` (#161) I get an error connecting to the GRASS GIS backend, e.g. https://openeo.mundialis.de. 

**Before** (tested locally with `git checkout 81c0fb98115555311f1a3c48f3114d7e5f917267`: 
![openeoweb_before](https://user-images.githubusercontent.com/8308401/125076287-06f51600-e0c0-11eb-887c-63e09a45e6c2.png)

**Now**:
![openeoweb_after](https://user-images.githubusercontent.com/8308401/125076338-15433200-e0c0-11eb-817e-c1eb57afea48.png)

Error in javascript console says:
```
TypeError: Cannot read property 'description' of null
    at fn (ConnectForm.vue?d071:3)
    at r (vue.runtime.esm.js:2590)
    at a.Me [as _t] (vue.runtime.esm.js:2686)
    at Tabs.vue?9702:1
    at a.Le [as _l] (vue.runtime.esm.js:2630)
    at a.s (Tabs.vue?9702:1)
    at a.t._render (vue.runtime.esm.js:3548)
    at a.r (vue.runtime.esm.js:4066)
    at nr.get (vue.runtime.esm.js:4479)
    at nr.run (vue.runtime.esm.js:4554) "render"
 ```

The openeo-grassgis-backend does not support OIDC Authentication yet.

**Comment by m-mohr** [comment]
If you don't support OIDC, you should not list it as supported. Your back-end lists it in the capabilities and redirects the request to the capabilities and that's invalid behavior. The Web Editor doesn't tolerate this behavior any longer and thus shows an error.

**Comment by mmacata** [comment]
Allright, I feared something like this. I will remove it there. Thanks for the hint.

**Comment by mmacata** [comment]
Sorry to reopen again - I removed the OIDC part from the capabilities so that they do not appear in the response anymore:
```diff
         },
-        {
-            "path": "/credentials/oidc",
-            "methods": [
-                "GET"
-            ]
-        },
         {
             "path": "/credentials/basic",
```
And also disabled the endpoint totally. The fatal error (same javascript error) still appears. Requests to the openeo-grassgis-driver are:
* http://127.0.0.1:5000/.well-known/openeo
* http://127.0.0.1:5000/api/v1.0/
* no request to /credentials/oidc anymore

Do you have any more hints?

**Comment by m-mohr** [comment]
I can connect to openeo.mundialis.de with the master version right now. There's no error.
We had a similar issue yesterday with EURAC, but the issue was some kind of dependency issue with npm.
Could you try deleting node_modules + package_lock.json and run `npm install` etc. again to check whether it still errors with freshly loaded dependencies?

**Comment by mmacata** [comment]
Now I get CORS errors? I rebuilt the docker image without cache and also tried it out locally without docker but no success. Which npm + node version are you using?

**Comment by m-mohr** [comment]
Hmm, that sounds like a connectivity issue or so. We could try to do a video call to debug, I can't reproduce it right now.

npm 7.10.0
node 14.3.0

**Comment by mmacata** [comment]
🤦 I had `http` instead of `https` in my drop-down server suggestion list... That explains the CORS error. The other error really seemed to disappear after clearing the cache. Now it works for master branch both ways: locally and with docker.

Thank you for your help!
