### ISSUE TITLE
Deploy fails

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-web-editor#175]
Deployment to https://open-eo.github.io/openeo-web-editor/demo/ fails.

**Comment by m-mohr** [comment]
@mmacata This is due to the Docker build, it seems.
Since adding the Dockerfile I'm getting build errors for each of my commits:
![image](https://user-images.githubusercontent.com/8262166/125592616-e396818b-8cf6-4018-b770-50bc330655e6.png)
Clicking the link directs me to a 404:
https://hub.docker.com/login/?next=/redirect/%3Fresource_uri%3D/api/audit/v1/action/c009a955-5e89-4024-8a49-10bd3acca08f/
Could you please look into it? What issue could that be?

**Comment by mmacata** [comment]
The build on Dockerhub fails. I made a clean new checkout of the repository and it fails as well:
```
11:05 $ npm run build

> @openeo/web-editor@0.8.0-rc.2 build
> npm run build:epsg && npx vue-cli-service build --report


> @openeo/web-editor@0.8.0-rc.2 build:epsg
> node src/build-epsg.js

node:internal/fs/utils:323
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'src/assets/epsg.json'
    at Object.openSync (node:fs:505:3)
    at Object.writeFileSync (node:fs:1535:35)
    at Object.<anonymous> (/home/ctawalika/repos/openeo/openeo-web-editor/src/build-epsg.js:9:4)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'src/assets/epsg.json'
}
```

is it working for you? Some days ago it was still successful.

**Comment by m-mohr** [comment]
Yes, the build is working for me...

**Comment by m-mohr** [comment]
Hmm... maybe that's an empty folder GitHub issue. I've added a file so that the folder will not be removed, let's see how it goes.

**Comment by mmacata** [comment]
Indenpendantly of the build, I saw that the last deploy action was running until [14 days](https://github.com/Open-EO/openeo-web-editor/actions/workflows/actions.yml) ago. In the [Github action file](https://github.com/Open-EO/openeo-web-editor/blob/master/.github/workflows/actions.yml#L5), there is a definition for 
```
on:
  push:
    branches:
      - dev
```
but there is no `dev` branch that I can see? Was there one before?

**Comment by mmacata** [comment]
The build is successful! Thanks! But I guess the deployment will not be triggered without the `dev` branch. Here you can see the gap of Github actions as well: https://github.com/Open-EO/openeo-web-editor/commits/master

**Comment by m-mohr** [comment]
Hah, good point! Thanks for catching it, indeed we had a dev branch before. I'll fix that!

**Comment by mmacata** [comment]
Great, now there are `2 successful checks` on each commit. I will close this.
