### ISSUE TITLE
Error when showing job results

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-web-editor#181]
Trying to show batch job results for the Terrascope backend fails with an error, see below.
I guess our STAC metadata could be incorrect, but can't figure out from the error what the problem is.

![image](https://user-images.githubusercontent.com/5937096/126622953-39e7c19a-c0cd-4ae4-94d6-a495f9085753.png)

**Comment by jdries** [comment]
I think I found it in jupter notebook, indeed invalid json:
`{'assets': {'openEO.tif': {'file:nodata': [nan],`

I did get a more clear error message in there:
![image](https://user-images.githubusercontent.com/5937096/126625312-708888ff-d828-4ed2-823c-ec02f20ff71e.png)

**Comment by m-mohr** [comment]
Oh, yes, that is this issue on the VITO back-end:

https://github.com/Open-EO/openeo-geopyspark-driver/issues/87

**Comment by m-mohr** [comment]
For the JS client, I made a quick fix to improve the error handling in this case, too.
