### ISSUE TITLE
Tour stays open when context changes

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-web-editor#196]
When a user is logged in, opens the tour and then disconnects, the tour bubble stays open:

![grafik](https://user-images.githubusercontent.com/17781682/131848516-7445104c-82f4-4b9d-94ca-2bfae78f7061.png)

**Comment by m-mohr** [comment]
Should be fixed, I hope I captured all cases where this is an issue (Modals, Connect <-> Login <-> IDE, Fullscreen).
