### ISSUE TITLE
Replace map with content area

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-web-editor#2]
The map on the right is only suitable for services. You should be able to switch between services and other data on the right, e.g. you could also show downloaded images or formatted JSON data.

**Comment by mkadunc** [comment]
For time series, it would also be nice to show a plot.
For zonal statistics, you could show polygons on a map with colors based on the computed values.

**Comment by m-mohr** [comment]
The basis for this is implemented. Editor provides a map view, image view and data view. Currently supports json, test, jpeg, png, gif and OpenEO web services. Needs further refinement for other data formats, e.g. zonal statistics, time series, ...
