### ISSUE TITLE
Improve drawing of bounding box for spatial extent

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-web-editor#212]
Currently, dragging one of the corners changes ALL corners which makes it extremely hard to select exactly the region you want.

Also, the current `cursor: move` is displayed as `cursor: pointer` on my Firefox 93 on Ubuntu 20. In the long run, `cursor: nesw-resize` etc. would be nicer anyway.

**Comment by m-mohr** [comment]
A completely new area chooser has been implemented in a dev version.
