### ISSUE TITLE
eo:bands `scale` rounding issue

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-web-editor#219]
(not sure where to report this, so feel free to move)

in Vito backend we have collection TERRASCOPE_S2_TOC_V2, which has `"scale": 0.0001` for a couple of bands
```json
"eo:bands": [
      {
        "aliases": [
          "TOC-B01_60M"
        ],
        "common_name": "coastal aerosol",
        "gsd": 60,
        "name": "B01",
        "offset": 0,
        "scale": 0.0001,
        "type": "int16",
        "unit": "1",
        "wavelength_nm": 442.7
      },
```

In the hub/editor/vuecomponents, this scale is rounded to `0`:

![Screenshot from 2021-11-03 12-08-38](https://user-images.githubusercontent.com/44946/140050042-14db75b1-f619-40e9-81cc-63257427bf7b.png)

**Comment by m-mohr** [comment]
The issue actually resides in stac-fields, which does round values by default.

**Comment by m-mohr** [comment]
Moved to https://github.com/stac-utils/stac-fields/issues/16
