### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-web-editor#221]
https://editor.openeo.cloud/ nor https://editor.openeo.org/ have a favicon

**Comment by m-mohr** [comment]
Yes, indeed. I simply don't have favicons for them and did not found those to be high prio.

**Comment by soxofaan** [comment]
What! not high prio?!??!11?!

**Comment by m-mohr** [comment]
😂 By the way, the same applies for mostly all openEO related pages. At least I couldn't find any with a favicon, except:
- https://openeo.cloud/ which uses the esa logo, but that's not ideal either
- https://open-eo.github.io/openeo-r-client/ which is the brave outsider

**Comment by m-mohr** [comment]
Actually, found a very simply way to make it work. Though I'd need a .ico file, but it also works to just refer to the logo that is included anyway.
