### ISSUE TITLE
Better handling when EGI is down

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-web-editor#223]
originally reported here: https://github.com/openEOPlatform/architecture-docs/issues/129#issuecomment-964029416

at the moment I can not log in on editor.openeo.org or editor.openeo.cloud because EGI seems down
 
I think `https://aai.egi.eu/oidc/.well-known/openid-configuration`  is the failing request that breaks the editor  flow

```
$ curl -i https://aai.egi.eu/oidc/.well-known/openid-configuration
HTTP/1.1 502 Bad Gateway
Server: nginx
Date: Tue, 09 Nov 2021 10:42:35 GMT
Content-Type: text/html
Content-Length: 166
Connection: keep-alive

<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Results are inconsistent: sometimes I get empty popup, sometimes I get popup that disappears immediately and "Network error" message
![Screenshot from 2021-11-09 11-49-31](https://user-images.githubusercontent.com/44946/140911051-06150045-e877-4cce-bde3-f9287443fe9c.png)

**Comment by m-mohr** [comment]
A bug fix has been implemented:

![image](https://user-images.githubusercontent.com/8262166/140969624-113a4474-e06c-4f34-b9d0-3684d7d69925.png)
