### ISSUE TITLE
copy collection id as string

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-web-editor#229]
I'm using  https://editor.openeo.cloud/ to browse through collections. When I find a collection I'd like to use, there is (as far as I know) no way to copy the collection id (to paste it in a script, notebook, email, chat, ...)

For example:
![Screenshot from 2022-01-07 10-15-40](https://user-images.githubusercontent.com/44946/148521303-479b9754-1977-40aa-9ddb-465c4c0dc4fe.png)
click and drag to select the text doesn't work (the whole box is dragged instead)

When clicking to open the popup, the box title is the only place with the id:
![Screenshot from 2022-01-07 10-17-53](https://user-images.githubusercontent.com/44946/148521671-de45e91b-e94e-4459-81f8-345f3c6e14c2.png)
click and drag to select the text doesn't work either (the popup is dragged around instead)

possible solutions:
- add a pure, non-interactive text field with the collection id to the popup
- add a button to copy the collection id to clipboard

**Comment by m-mohr** [comment]
I had the same issue recently and I am also always annoyed by it. I'll implement a copy to clipboard button for Modal titles ;-)

**Comment by m-mohr** [comment]
Implemented, will be deployed soon.

**Comment by m-mohr** [comment]
Deployed now as v0.10.1

**Comment by soxofaan** [comment]
nice, great response time :)
