### ISSUE TITLE
Formula editor removes useful brackets

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-web-editor#235]
Steps to reproduce the issue:
1. Insert an apply process
2. Insert the following formula in the formula editor `10*log(x/(4*19), 10)` and close it
3. Now the process graph is correct.
4. Reopen the formula editor: the curly brackets have been removed, if you press insert again the process graph will be wrong (compared to our initial formula)

**Comment by m-mohr** [comment]
Should be fixed in v0.10.3 - This may lead to some unnecessary brackets, but better too much than not enough.
