### ISSUE TITLE
/processes not shown after disconnecting and reconnecting

### ISSUE THREAD

**Issue by dthiex** [Open-EO/openeo-web-editor#245]
Steps to reproduce (works only 1st time):

1. Go to https://editor.openeo.org/
2. Connect to any openEO backend e.g. "https://openeo.cloud"
3. Login using EGI Check-in
4. Disconnect (top right)
5. Connect to any backend (can be the same backend again)

What happens:
The editor opens and shows 
- collections, UDF Runtimes and Export File Formats from the backend selected in step 2
- no processes

**Comment by m-mohr** [comment]
Thanks for the report, the issue has been fixed.
