### ISSUE TITLE
Don't open metadata when viewing results

### ISSUE THREAD

**Issue by dthiex** [Open-EO/openeo-web-editor#265]
> Yes, I'm planning to not open the metadata at all.

Follow up from https://github.com/Open-EO/openeo-web-editor/issues/263#issuecomment-1152096843

**Comment by m-mohr** [comment]
Yes, if the roles are set, assets with role "metadata" should be excluded from being opened in the viewer.

**Comment by m-mohr** [comment]
Should be available at editor.openeo.org - Could you check whether it works for you, @dthiex ? Make sure that you don't load the editor from cache...

**Comment by dthiex** [comment]
> Could you check whether it works for you, @dthiex ?

Yes, works for me (metadata is not opened automatically upon job finish. 

Btw. do I remember correctly that the preview (View results) "only" works for gtiffs? I created some png as output and am stuck (since minutes) with a Loading image screen.

![grafik](https://user-images.githubusercontent.com/60705209/181575610-b9a3819c-aa0a-4cc6-bff3-ccf61ead192f.png)

**Comment by m-mohr** [comment]
The PNG should also open... mhh... Any errors in the console or so?

**Comment by dthiex** [comment]
> Any errors in the console or so?

Yes, sure! Sorry for the not so helpful report... 

Below the console error and I also found the underlaying issue. We create "wrong" pngs with more then 3 output bands. Opening such a png in QGIS works and there is also data in the bands >3. I checked the Vito implementation and saw that they "just" export the first 3 bands in such a case. Would that also be for you the expected behaviour? 

![grafik](https://user-images.githubusercontent.com/60705209/181690761-699ee7b1-8184-4a01-9a5b-b2724eca831f.png)

**Comment by m-mohr** [comment]
Yeah, I think PNGs should be Grayscale, RGB or RGBA. Otherwise, most software (especially) browsers can't read it by default.

By the way, the error above doesn't originate from reading the image directly. The error is just from hovering the canvas and trying to read pixel values from it.

**Comment by dthiex** [comment]
> Yeah, I think PNGs should be Grayscale, RGB or RGBA. Otherwise, most software (especially) browsers can't read it by default.

Makes sense (also for jpg). Created an internal issue for this so we improve here.

> By the way, the error above doesn't originate from reading the image directly. The error is just from hovering the canvas and trying to read pixel values from it.

Okay, but the image not loading is still due to the mentioned problem.

**Comment by m-mohr** [comment]
@dthiex I tried to make the image loading more robust. Could you check what happens now at editor.openeo.org (refresh cache pls)? I don't have an image at hand to test what happens with "erroneous" images...

**Comment by dthiex** [comment]
> Could you check what happens now at editor.openeo.org (refresh cache pls)?

Checked and it now doesn't load infinite but I get a "Viewer error" (in the notification panel that disappears after a few seconds again). 

Here a 23 band png in case you need it for further testing: ![23_band_png](https://user-images.githubusercontent.com/60705209/182152227-266208fe-9302-4376-b04c-aa332ae83f6e.png)

**Comment by m-mohr** [comment]
Just "Viewer Error" or is there more information available?

Anyway, it is intentional that it gives an error because the Browser can't read the PNG files. So the improvement is that it errors instead of loading forever. @dthiex 

Thanks for the image, will have a look.

**Comment by dthiex** [comment]
> Just "Viewer Error" or is there more information available?

I get this notification in the editor 

![grafik](https://user-images.githubusercontent.com/60705209/182163593-25bbabf0-2b0d-461e-a0c6-f3716ce4cd4f.png)

and this console error

![grafik](https://user-images.githubusercontent.com/60705209/182164024-d11a9600-f376-479a-97d9-5efc4e5834d4.png)

**Comment by m-mohr** [comment]
Okay, I can't get any useful error messages from the browser when loading images. So it should now show a generic "Failed to load the image" error instead of "Viewer Error". That seems the best I can do.

**Comment by dthiex** [comment]
@m-mohr Yes, I am now getting the "Failed to load the image" error message which is I think already a good improvement as it at least gives some idea to where the error is.
