### ISSUE TITLE
Request failed with AggregateError but data is downloaded correctly

### ISSUE THREAD

**Issue by dthiex** [Open-EO/openeo-web-editor#267]
Executing this PG downloads me the data correctly but the Editor throws this error. In the network responses I don't see anything wrong reported by the backend. This happens only on FF (might be connected to what we already discovered, that  FF seems to be not able to send the request to the local blob).

**PG**
```
{
  "process_graph": {
    "1": {
      "process_id": "load_collection",
      "arguments": {
        "id": "COPERNICUS_30",
        "spatial_extent": {
          "west": 14.503132250376241,
          "south": 45.98989222284457,
          "east": 14.578437275398317,
          "north": 46.04381770188389
        },
        "temporal_extent": null,
        "properties": {}
      }
    },
    "2": {
      "process_id": "save_result",
      "arguments": {
        "data": {
          "from_node": "1"
        },
        "format": "GTIFF"
      },
      "result": true
    }
  },
  "parameters": []
}
```

**Error in Editor**
```
Request failed
- Data:
  - Errors:
  -  Name: AggregateError
- ID: 
```

**FF Console Error**
![image](https://user-images.githubusercontent.com/60705209/177317672-83b15117-d896-4404-ad61-ab19e0e6a3f3.png)

**Comment by m-mohr** [comment]
Yes, this is very likely the blob issue in FF again...

**Comment by m-mohr** [comment]
I've implemented and deployed a workaround for editor.openeo.org. For me this works, for you as well @dthiex ?

**Comment by dthiex** [comment]
Locally it worked but in the deployed version it's the same before. @m-mohr Did you really deploy a new version already? I couldn't see a new version tag or a release note.

**Comment by m-mohr** [comment]
I did not check the deployed version, only locally. Anyway, if it is not working now it's a Firefox issue that I can't work around.

Deployments work automatically after commits. Releases are not made on each commit but once in a while...

**Comment by dthiex** [comment]
> So it seems there was an issue with the deploy procedure, I reran it and now it also works on editor.openeo.org for me.

Indeed it works now! Thanks for fixing this.
