### ISSUE TITLE
Removing connections in Visual Process graph builder

### ISSUE THREAD

**Issue by Sijoma** [Open-EO/openeo-web-editor#27]
It would be good to make it easier to remove connections in the visual process graph builder. I know that the functionality is in the current version but I cannot do it currently without switching to the code view.

**Comment by Sijoma** [comment]
If I select the connector (edge), I also can´t delete it with "ENTF" which is (CMD + Backspace) on Mac.

**Comment by Sijoma** [comment]
I finally got it detached. If I increase the length of the edge, it is easier to drag and detach the connection. It seems like if you click on the last 25% of the connection and drag it correctly detaches.

**Comment by m-mohr** [comment]
I guess that's an issue with Mac having another keystroke for deleting. Will check on Monday...

**Comment by m-mohr** [comment]
Delete works as expected on a MacBook, it can be used with Fn + Backspace button.

To make it easier for users, there's now also a delete button in the toolbar.
