### ISSUE TITLE
allow entering process graph without "process_graph" wrapper

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-web-editor#271]
The code editor requires that the process graph JSON is wrapped in `{"process_graph": ...}`
otherwise, when you try to switch to "visual mode", you get this "Process invalid" error:

![Screenshot from 2022-08-11 14-56-34](https://user-images.githubusercontent.com/44946/184138599-7844f352-7896-4288-a526-bf5fd1aa4960.png)

Very often, when I do user support, the user shares their process graph without the `{"process_graph": ...}` wrapper.
Can't we just support that format too in the editor?

**Comment by m-mohr** [comment]
That's invalid according to the spec. I'd rather say, please implement the other clients in a way that they don't export invalid processes:
- https://github.com/Open-EO/openeo-python-client/issues/209
- https://github.com/Open-EO/openeo-python-client/issues/209
- https://github.com/Open-EO/openeo-r-client/issues/54

**Comment by soxofaan** [comment]
Regarding re-opening https://github.com/Open-EO/openeo-python-client/issues/155 : I commented on that ticket itself.
I also closed https://github.com/Open-EO/openeo-python-client/issues/209 as a duplicate of that.
