### ISSUE TITLE
resample_spatial parameters bug

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-web-editor#274]
When inserting the resample_spatial process, if you edit the parameters you would automatically get a projection selected in the respective field. However, I guess it should be set to null as default, since it's not a mandatory parameter.

![image](https://user-images.githubusercontent.com/31700619/188420348-0bbd9e96-eced-4dcf-a033-fddc11aa71cc.png)

**Comment by m-mohr** [comment]
Thanks, will check. Which back-end is this for?

**Comment by clausmichele** [comment]
Well, I'm using the Eurac back-end (currently implementing resample_spatial) but I guess it's the same for the others.

**Comment by m-mohr** [comment]
Looking at https://processes.openeo.org/#resample_spatial I see that 0 is the default value (means: no change) so the behavior is correct.

**Comment by clausmichele** [comment]
Yes, the default for the projection is null, but if you open the pop-up to modify the process parameters it automatically select the EPSG:2000

**Comment by m-mohr** [comment]
What else should it select?

Default is "0" (not "null") and that's the only value that I can work with at that time. If you then choose to select EPSG code, then you need to choose something and it automatically select the first entry in the list, which is normal in UIs if no actual value is provided. I could arbitrarily choose something else, but that's like not better than the first element. 

I'm not exactly sure what your proposal for improvement is?

**Comment by m-mohr** [comment]
My fault, I looked at resolution instead of projection. Will be fixed.

**Comment by m-mohr** [comment]
Can't reproduce on VITO: Are you on the latest version of the Web Editor? Is your schema correctly returned from the back-end? It might be that "null" as default value get's removed by your back-end as it thinks null means "don't serialize to JSON", I've seen that before in the Java implementation.

**Comment by clausmichele** [comment]
Found the problem, the resample_spatial process in our back-end is an outdated version. So the bug it's on our side not on the Web editor sorry!
https://github.com/Open-EO/openeo-spring-driver/issues/65
