### ISSUE TITLE
Add copy & paste buttons to Editor

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-web-editor#276]
Based on https://github.com/Open-EO/openeo-web-editor/pull/273#issuecomment-1234077364 and https://github.com/Open-EO/openeo-vue-components/issues/48

Copy/Paste buttons in the Model Builder (and Text Editor) would be nice.
Depending on the scope, different things may happen:
- [x] Box (1+) selected: Copy box
- [x] Box(es) in clipboard: Paste box(es)
- [x] Nothing selected: Copy full process JSON
- [x] Process JSON in the clipboard: Paste that
- [ ] Edge selected: Copy nothing but give a message that explains in which cases you can copy

**Comment by pierocampa** [comment]
+1 to this.
And I would also add: <kbd>Ctrl</kbd> + <kbd>C</kbd> / <kbd>Ctrl</kbd> + <kbd>V</kbd> key bindings listeners.

**Comment by m-mohr** [comment]
Parts of this are already supported, including key bindings (see the added todo list above). Getting copy/paste for individual boxes would indeed be very useful, but needs a bit more work.

**Comment by clausmichele** [comment]
Hi @m-mohr, I just tried this feature but it seems that it doesn't work on Firefox:
![image](https://github.com/Open-EO/openeo-web-editor/assets/31700619/ce9dba85-2625-409a-9e60-c263c54e5903)


Also tried in Opera and there it works fine.

**Comment by m-mohr** [comment]
Yes, that's a known issue/limitation in Firefox, unfortunately.
