### ISSUE TITLE
Error 400: no jobs are available at the moment

### ISSUE THREAD

**Issue by pierocampa** [Open-EO/openeo-web-editor#282]
This error keeps popping up (lower-right corner popup) when you enter the editor and have no batch jobs saved in your processing library.

I believe having an empty jobs library should not even raise an error to the end-user, or at least it should be downgraded to a warning alert, and should also be presented only once to the user.

----

Web Editor v0.11.3 here.

**Comment by m-mohr** [comment]
This looks like a back-end issue. An empty job list should never return a 400 status code. Please report this to the corresponding back-end.
