### ISSUE TITLE
Lost link with job when clearing its content

### ISSUE THREAD

**Issue by pierocampa** [Open-EO/openeo-web-editor#285]
While editing an existing (saved) job, if you clear out its content from the "Code" tab, the panel loses the link to the job and you land into a new unsaved job. This does **not** happen if you blank out the blocks from the graph view.

I believe this is not the expected behaviour, though I might be wrong!

(Not sure also if this should be moved to the [openeo-vue-components](./openeo-vue-components))

**Comment by m-mohr** [comment]
Thanks for the report. This sounds like a bug and is indeed correct in the Web Editor issue tracker. :-)

**Comment by m-mohr** [comment]
@pierocampa  By the way, what do you mean with clearing out? Do you use the "clear button" or do you simply remove the JSON from the textbox?

**Comment by pierocampa** [comment]
I mean manually clearing the JSON text. !

**Comment by m-mohr** [comment]
This has been fixed
