### ISSUE TITLE
web service tab is only updated upon login

### ISSUE THREAD

**Issue by dthiex** [Open-EO/openeo-web-editor#286]
As web services can also be created and deleted outside of the editor (from a notebook, direct request...) it would be nice if this (the list of available web services) could either be manually ("refresh" web service) or automatically (similar to how we already call the jobs endpoint) updated.

Discovered when working on: https://github.com/Open-EO/openeo-python-client/pull/339 which adds the functionality to preview process graphs directly in a notebook.

**Comment by m-mohr** [comment]
Each tab is updated every two minutes (if not configured differently in `dataRefreshInterval`) or when the tab is opened and the last refresh was more than two minutes ago.

**Comment by m-mohr** [comment]
The refresh button is back :-)

**Comment by dthiex** [comment]
> Each tab is updated every two minutes (if not configured differently in dataRefreshInterval) or when the tab is opened and the last refresh was more than two minutes ago. Potential duplicate of https://github.com/Open-EO/openeo-web-editor/issues/231.

Seems like I didn't have enough patience here and got mislead by the 10 seconds we have for active jobs. Anyway, find the refresh button very handy and think it's good to have it (next to the automatic refresh already in place). Thanks for adding it back ;)
