### ISSUE TITLE
Latest container does not work

### ISSUE THREAD

**Issue by danielFlemstrom** [Open-EO/openeo-web-editor#287]
`mundialis/openeo-web-editor:latest` generates an error for the process (pseudo form)
loadcollection->save (geotiff)

<img width="247" alt="image" src="https://user-images.githubusercontent.com/12410550/205238959-54dbcb57-0a01-447a-8495-ed517d2a7e1f.png">

None of the available hashes between the one used in `https://editor.openeo.org`(0.11.4) and 78257122a486ca19ca46c1944432d9d9afa0532c gives that error so i am not sure why `:latest`complains.. 

Is there a way to see which commit hash `:latest` corresponds to?

**Comment by m-mohr** [comment]
This is weird, doesn't look like it should be docker related. It basically says it can't access the GeoTiff file, which can have a couple of issues:
- General connectivity issues of the local computer
- Network access through docker doesn't work correctly
- CORS issues on the server side
- Some dependency of the Web Editor has a malfunction
- A bug in the Web Editor itself.
- ...

Does it work in the most recent deployed version at editor.openeo.org?

**Comment by danielFlemstrom** [comment]
Yes and all check-ins after that version. So with a bit of luck, re-generating the :latest would fix it.
I used the same EO-Server and the same process tree to test.

From: Matthias Mohr ***@***.***>
Date: Friday, 2 December 2022 at 11:41
To: Open-EO/openeo-web-editor ***@***.***>
Cc: Daniel Flemström ***@***.***>, Author ***@***.***>
Subject: Re: [Open-EO/openeo-web-editor] Latest container does not work (Issue #287)

This is weird, doesn't look like it should be docker related. It basically says it can't access the GeoTiff file, which can have a couple of issues:

  *   General connectivity issues of the local computer
  *   Network access through docker doesn't work correctly
  *   CORS issues on the server side
  *   Some dependency of the Web Editor has a malfunction
  *   A bug in the Web Editor itself.
  *   ...

Does it work in the most recent deployed version at editor.openeo.org?

**Comment by mmacata** [comment]
Hi @danielFlemstrom, the `latest` tag is updated for every release which was `v0.11.0` ~ six month ago. So the same error should appear for `mundialis/openeo-web-editor:v0.11.0` and should already have been there this long.
So to be sure what's inside, it might makes sense to pin version either to a commit hash or to a released version.

**Comment by m-mohr** [comment]
The issue you are seeing is likely fixed by #267.
And it's probably time for a 0.12.0 release :)

**Comment by mmacata** [comment]
We pass the decision to what latest should be to [a github action](https://github.com/Open-EO/openeo-web-editor/blob/master/.github/workflows/docker.yml#L26-L33) called [docker/metadata-action](https://github.com/docker/metadata-action#latest-tag) and simply use the default behaviour of it. 

So I also think that it would be time for a new release (:

**Comment by m-mohr** [comment]
Fixed the remaining bugs for 0.12.0 and released it. The container should be updated in some minutes.

**Comment by mmacata** [comment]
`mundialis/openeo-web-editor:latest LAST PUSHED 19 hours ago` :+1: 
and hash is identical to [v0.12.0](https://hub.docker.com/layers/mundialis/openeo-web-editor/v0.12.0/images/sha256-d836ea2cbc4432fd54f6f4f35102b97625b7f1b1654a82141b3e8bb2b7c2f29f?context=repo)
