### ISSUE TITLE
parameters of function stretch_colors are stored as string in the process graph

### ISSUE THREAD

**Issue by Sijoma** [Open-EO/openeo-web-editor#29]
The parameters of the function stretch_colors are stored as a string in the process_graph. However, at least the GEE back-end expect those values to be a number.

code: 2103
id: "1552571249580"
message: "The value specified for the process argument 'min' in process 'stretch_colors' is invalid: instance is not of a type(s) number"
url: "https://open-eo.github.io/openeo-api/errors/#openeo-error-codes"

**Comment by m-mohr** [comment]
Fixed, thanks for reporting the issue.
