### ISSUE TITLE
upload button for area of interest

### ISSUE THREAD

**Issue by Pratichhya** [Open-EO/openeo-web-editor#292]
Since in most of the scenario user wishes to directly upload their area of interest as shapefile or GeoJson or Kml/kmz, is it possible to add an upload button to the map view of the openeo web editor? (that will be in addition to already available draw polygon, line etc.)

**Comment by m-mohr** [comment]
As long as the backend implementation supports uploading files in general and the file formats as input file formats you can upload them in the Web Editor. Then they reside on the backend and could be used in processes. I assume you are using openEO Platform? In this case, this needs to be adressed with openEO Platform directly, e.g. via a forum post.

In the Web Editor itself it will be hard to read shapefiles as it would need to be read directly in the browser, but shapefiles are multiple files so hard to manage. You can already copy&paste GeoJSON into the Code tab of the GeoJSON editor, but I'll also add a possibility to drag&drop GeoJSON files directly. For KML I'll need to check whether there's a good library for reading it.

**Comment by m-mohr** [comment]
I've implemented drag&drop for KML and GeoJSON, so it should be easier now to use those files for the AOI. Please see the demo below for details:

![kml](https://user-images.githubusercontent.com/8262166/209120629-5f2e7d3c-d9ab-438a-9ec3-a9dda66e395c.gif)
