### ISSUE TITLE
Execution of UDP in web editor not supported

### ISSUE THREAD

**Issue by JanssenBrm** [Open-EO/openeo-web-editor#295]
Using the wizard process of the OpenEO web editor, you can open up a UDF, fill in the parameters and execute the process. For example: 

https://editor.openeo.org/?server=https://openeo.vito.be&namespaces=u:ecce9fea04b8c9c76ac76b45b6ba00c20f211bda4856c14aa4475b8e8ed433cd#@egi.eu&wizard=UDP&wizard-process=NBR@u:ecce9fea04b8c9c76ac76b45b6ba00c20f211bda4856c14aa4475b8e8ed433cd@egi.eu 

However, when executing the process, an error occurs with the following message:
`Process with identifier 'NBR' is not available in namespace 'u:ecce9fea04b8c9c76ac76b45b6ba00c20f211bda4856c14aa4475b8e8ed433cd@egi.eu'.`

The above process results in the following processing graph:
```json
{
  "process_graph": {
    "NBR": {
      "process_id": "NBR",
      "namespace": "u:ecce9fea04b8c9c76ac76b45b6ba00c20f211bda4856c14aa4475b8e8ed433cd@egi.eu",
      "arguments": {
        ...
      },
      "result": true
    }
  }
}
```
To fix the error, you can change the namespace value to the full URL.
```json
{
  "process_graph": {
    "NBR": {
      "process_id": "NBR",
      "namespace": "https://openeo.vito.be/openeo/1.1/processes/u:ecce9fea04b8c9c76ac76b45b6ba00c20f211bda4856c14aa4475b8e8ed433cd@egi.eu/NBR",
      "arguments": {
        ...
      },
      "result": true
    }
  }
}
```

I am not sure if this is an issue in the editor or elsewhere. We've also detected the same behavior in the Python client (https://github.com/Open-EO/openeo-python-client/issues/357 ). The inconsistent usage of the namespace could become confusing for users.

**Comment by m-mohr** [comment]
I can't reproduce this as I don't have access to this namespace, but if it's also present in the Python client this sounds very much like a back-end implementation issue to me. Also, throughout the JS code there's no such error message defined in code so it seems to come from the back-end.
