### ISSUE TITLE
No feedback for namespace/wizard query parameters

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-web-editor#296]
The following link doesn't give any feedback to the user, it just opens the Web Editor:
https://editor.openeo.org/?server=https://openeo.vito.be&namespaces=u:ecce9fea04b8c9c76ac76b45b6ba00c20f211bda4856c14aa4475b8e8ed433cd#@egi.eu&wizard=UDP&wizard-process=NBR@u:ecce9fea04b8c9c76ac76b45b6ba00c20f211bda4856c14aa4475b8e8ed433cd@egi.eu

The Editor should indicate why the query parameters were not taken into account (also: the wizard parameters just disappear). 
Reason is likely that I can't access the namespace / the process in the namespace.

**Comment by m-mohr** [comment]
What I found:
- The link is malformed and should be: https://editor.openeo.org/?server=https://openeo.vito.be&namespaces=u:ecce9fea04b8c9c76ac76b45b6ba00c20f211bda4856c14aa4475b8e8ed433cd@egi.eu&wizard=UDP&wizard~process=NBR@u:ecce9fea04b8c9c76ac76b45b6ba00c20f211bda4856c14aa4475b8e8ed433cd@egi.eu
- Using the link above it works as expected, even with an invalid process.

**Comment by JanssenBrm** [comment]
It definitely sounds familiar. However, it is solved!
