### ISSUE TITLE
Feature request: bounding box from address/city for load_collection

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-web-editor#298]
It would be cool to have the possibility to select a bounding box (or geoJSON polygon) typing the name of a city instead of zooming in and selecting manually.
OpenStreetMaps would allow us to do that, with a query like:
https://nominatim.openstreetmap.org/search?q=Trento&format=json&polygon=1&addressdetails=1

not sure how to handle results that return multiple items. Maybe we could show the "display_name" field and let the user choose from the proposed ones.

**Comment by m-mohr** [comment]
Yeah, I also would like to get that. For the openEO Web Editor this could be an option, but for the openEO Platform Editor we would likely need a commercial license.

**Comment by m-mohr** [comment]
Potential plugin to use: https://github.com/jonataswalker/ol-geocoder

**Comment by clausmichele** [comment]
Something like this was already available in the openEO Android app, was that using google?

**Comment by m-mohr** [comment]
I guess they had a paid subscription for Solenix...

**Comment by clausmichele** [comment]
It seems they were using OSM: https://github.com/Open-EO/openeo-demonstrator-mobile-app/search?q=location
But again, as you said we can't use it for openEO Platform since it's commercial I guess.
Here there are some commercial alternatives listed:
https://help.openstreetmap.org/questions/77653/switch-to-commercial-nominatim-service-by-simply-exchanging-api-url-in-my-program

**Comment by m-mohr** [comment]
Geocoding has been implemented.

For openEO Platform we may consider https://rapidapi.com/GeocodeSupport/api/forward-reverse-geocoding/pricing later.

**Comment by clausmichele** [comment]
Wonderful! It works fine! You're too efficient Matthias 🥇
