### ISSUE TITLE
CORS guidelines

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-web-editor#306]
We're trying to set up a custom deployment of the editor and noticed a problem when trying to do OIDC auth: 

after submitting the OIDC popup, we get an error message 
> Sorry, the authentication server is not available right now.

In the dev tools I see
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://oidc-provider.example/token. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

So this probably can be fixed with proper CORS headers

I was wondering if this requirement is documented somewhere in web editor setup docs?

**Comment by m-mohr** [comment]
No, because I think the normal CORS recommendations from the API spec apply: 
https://api.openeo.org/#section/Cross-Origin-Resource-Sharing-(CORS)

**Comment by soxofaan** [comment]
> No, because I think the normal CORS recommendations from the API spec apply

That's indeed for CORS setup between the web editor and a openEO back-end.

In this case however we're having a CORS problem between the web editor and the OIDC provider (e.g. Keycloak here). 
My initial thought was that this had to be fixed in the web editor deployment (e.g. because https://editor.openeo.org and https://editor.openeo.cloud return header `Access-Control-Allow-Origin: *`), but it turns out we actually have to make sure keycloak reaturns these CORS headers
