### ISSUE TITLE
Better copy for broken webapp

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-web-editor#312]
https://github.com/Open-EO/openeo-web-editor/blob/366e9d71e845e6ca69db2edbf2c7b9f0a72a2bc8/public/index.html#L18-L20

If the webapp deployment is broken in some way (e.g caching issue with one of the necessary JS files), a user just gets
```
Sorry, this website requires a modern browser. Please update your browser or use Google Chrome or Mozilla Firefox as alternative. 
```

![image](https://github.com/Open-EO/openeo-web-editor/assets/44946/4184e968-e01d-46a8-a0af-dc9b045880bb)

This is misleading and confusing (e.g they get this also in one of the suggested browsers).

**Comment by soxofaan** [comment]
A couple of possible improvements:
- improve error message to make it clearer that it can also be a servers-side/webapp issue (not only because of used browser)
- improve detection of what is actually wrong
- Allow for some theming/styling of the error message
- Allow for customization of the error message (e.g. link to a documentation page or some support tool)

**Comment by m-mohr** [comment]
Happy to accept PRs.

**Comment by soxofaan** [comment]
let's start with just improving the error message a bit #314
