### ISSUE TITLE
load_stac - save_result -> error

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-web-editor#315]
@m-mohr I just found this behaviour: probably there's something in the `load_stac` definition that makes it conceptually incompatible with `save_result`?

![image](https://github.com/Open-EO/openeo-web-editor/assets/31700619/302fb818-b801-495a-afb2-4252652ad2d0)

**Comment by m-mohr** [comment]
Can it be that the v2.0.0 and v1.0.0 way of specifying the processes is mixed? (i.e. subtype datacube vs. subtype raster-cube?)

**Comment by clausmichele** [comment]
Probably yes, from the definition here load_stac returns a datacube and not a vector-cube: https://github.com/Open-EO/openeo-processes/blob/master/proposals/load_stac.json

The example above was using the VITO back-end. Same issue with the aggregator openeo.cloud or the CDSE.

**Comment by m-mohr** [comment]
Yes, that's the issue. The Web Editor doesn't understand yet that datacube and raster-cube (or vector-cube) are basically the same thing. Waiting for SAP10 to bring funding for v2 support.

**Comment by m-mohr** [comment]
This has been fixed.
