### ISSUE TITLE
bounding box from address/city for load_collection - no internet connection

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-web-editor#318]
Recently I noticed that this functionality doesn't work any more:
![image](https://github.com/Open-EO/openeo-web-editor/assets/31700619/6f072caf-d98f-412d-960c-4b4e6ead4237)

**Comment by m-mohr** [comment]
Looks like the lookup service is down. I assume I have to disable the functionality unless we find another free service offering this.

**Comment by m-mohr** [comment]
The URL of the geocoder has changed.

You need to update the `geocoder` value in the config.

The default was `https://nominatim.openstreetmap.org/search/`
It needs to be `https://nominatim.openstreetmap.org/search` (just remove the slash at the end)
