### ISSUE TITLE
ReferenceError: assignment to undeclared variable process

### ISSUE THREAD

**Issue by SerRichard** [Open-EO/openeo-web-editor#327]
Version: 0.14.0-beta.1

When trying to add a process using the drag and drop in the [web editor ](editor.openeo.org), the following error occurs

`Uncaught (in promise) ReferenceError: assignment to undeclared variable process`

Complaint seems to originate from _loadProcess index.js:283_

I'm guessing `process = cx.getters.processes.get(id, namespace);` should be
`let process = cx.getters.processes.get(id, namespace);` , but I'm not sure as it's unchanged for years?

I've checked it on eodc (dev + prod )  & vito ( prod ) servers and it's present on all.

**Comment by m-mohr** [comment]
Thanks for the report.
I guess that was always a bug but the transpilers have fixed that implicitly before, but don't do it anymore.
Your guess was correct, I fxied it.
