### ISSUE TITLE
Web editor raises warning with process definition v2.0.0-rc.1

### ISSUE THREAD

**Issue by ValentinaHutter** [Open-EO/openeo-web-editor#328]
In the eodc backend, we updated the process definitions to be compliant with v2.0.0. This is fine for the backend specific [editor](https://editor.openeo.org/?server=https%3A%2F%2Fopeneo-dev.eodc.eu%2Fopeneo%2F1.1.0) but leads to a problem with the aggregator: 

The loading of the collection is still expected to return a `raster-cube`, while our backend specific processes such as `sen2like`expect a `datacube`. For the processes that are available on other backends as well, the old specification is used, so these do not show the warning. 

Would it be an option to switch off this check or to allow a `raster-cube` when a `datacube` is expected? 

The warning looks like this: 

![Screenshot 2024-10-16 080457](https://github.com/user-attachments/assets/c06513d6-480a-4081-bfde-cddd1d68f6a5)

**Comment by ValentinaHutter** [comment]
The process_graph to recreate the issue is: 

```
{
  "process_graph": {
    "load1": {
      "process_id": "load_collection",
      "arguments": {
        "id": "SENTINEL2_L1C"
      }
    },
    "sen2": {
      "process_id": "sen2like",
      "arguments": {
        "data": {
          "from_node": "load1"
        }
      }
    },
    "save3": {
      "process_id": "save_result",
      "arguments": {
        "data": {
          "from_node": "sen2"
        },
        "format": "NETCDF"
      },
      "result": true
    }
  },
  "parameters": []
}
```

**Comment by ValentinaHutter** [comment]
@m-mohr do you have any inputs on that? :)

**Comment by ValentinaHutter** [comment]
looks like this has been resolved now!

**Comment by m-mohr** [comment]
Sorry, I didn't see this issue before. This was solved as part of the SAP10 work, indeed :-) Happy that it works.
