### ISSUE TITLE
When clicking the "eye" to view the results i get TypeError: o.A.confirmOpenAll is not a function 

### ISSUE THREAD

**Issue by danielFlemstrom** [Open-EO/openeo-web-editor#329]
0.14.0-beta.2

When I click the eye i get this error:

```
TypeError: o.A.confirmOpenAll is not a function
    showJobResults Viewer.vue:207
    VueJS 2
    broadcast EventBusMixin.js:28
    viewResults JobPanel.vue:348
 event handler for "viewJobResults"
```

**Comment by christophfriedrich** [comment]
That is the only function that doesn't have the `static` keyword in utils.js:

https://github.com/Open-EO/openeo-web-editor/blob/be63d8fef0075b47dfe9faea1572ff6359b45fb3/src/utils.js#L416

I guess this is the issue, as it's not a class function then, making it unavailable to call on `Utils` in the viewer:

https://github.com/Open-EO/openeo-web-editor/blob/be63d8fef0075b47dfe9faea1572ff6359b45fb3/src/components/Viewer.vue#L207

**Comment by m-mohr** [comment]
Interesting, I don't get an error in the deployed instance.
Nevertheless, the static keyword is indeed missing as indicated by @christophfriedrich.
Fixed on master.
