### ISSUE TITLE
Action when clicking on parameter titles

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-web-editor#35]
Currently, dragging connections between boxes can be initiated by clicking and holding on a parameter title or the little rectangle in front of it. In my opinion, the latter is enough and the former rather confusing.

Instead, it would be helpful if (single or double) clicking on the parameter title would open the configuration modal and (at least for text inputs) focus the corresponding input field.

**Comment by m-mohr** [comment]
Thanks, good idea. Implemented.
