### ISSUE TITLE
Visual Model output of Process Graph gives the from_node field as Integer, while it should be a string

### ISSUE THREAD

**Issue by prateekbudhwar** [Open-EO/openeo-web-editor#37]
I am using the web editor 0.4.0-beta.4, and when I create a process graph in visual model as shown in the Image below attached, I get the following JSON format of process graph as below, where the from_node field should be in String format but giving Integer format. 
![Visual Model](https://user-images.githubusercontent.com/690102/63494788-bae65b80-c4be-11e9-8978-423dd28af6dd.png)

{
  "1": {
    "process_id": "load_collection",
    "arguments": {
      "id": "openEO_S2_32632_20m_L2A",
      "spatial_extent": {
        "west": 11.286732,
        "south": 46.466714,
        "east": 11.389729,
        "north": 46.513988
      },
      "temporal_extent": [
        "2018-06-23T00:00:00Z",
        "2018-06-23T00:00:00Z"
      ],
      "bands": null,
      "properties": null
    }
  },
  "2": {
    "process_id": "save_result",
    "arguments": {
      "data": {
        "from_node": 4
      },
      "format": "GTiff",
      "options": {}
    },
    "result": true
  },
  "3": {
    "process_id": "ndvi",
    "arguments": {
      "data": {
        "from_node": "1"
      }
    }
  },
  "4": {
    "process_id": "max_time",
    "arguments": {
      "data": {
        "from_node": 3
      }
    }
  }
}

**Comment by m-mohr** [comment]
Thanks for the report. I fixed it in master.

Please note that old process graphs will not be updated automatically as the references (from_node, from_argument) are only re-generated once the edge is newly created in the visual builder.
