### ISSUE TITLE
Native support for GeoTiffs and COGs

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-web-editor#38]
Add native (browser-based, serverless) support for GeoTiffs and COGs.

**Comment by m-mohr** [comment]
Related: https://github.com/cogeotiff/www.cogeo.org/issues/36

**Comment by m-mohr** [comment]
So I've experimented a bit with the new experimental support for COGs that is available for OpenLayers here https://github.com/openlayers/openlayers/pull/12008:

Here's how to link against the branch: https://github.com/openlayers/openlayers/pull/12008#issuecomment-822341709

One issue that came up is that the CORS policy for the GeoTiffs needs to allow the HTTP range requests at the back-end side:
`Access to fetch at 'https://openeo-dev.vito.be/openeo/1.0/jobs/2abbf817-a558-41e5-a81c-3b2acfef5852/results/.../openEO.tif?expires=1628068876' from origin 'http://localhost' has been blocked by CORS policy: Request header field range is not allowed by Access-Control-Allow-Headers in preflight response.`

After disabling CORS in Chrome (`chrome.exe --user-data-dir="C:/Chrome dev session" --disable-web-security`) I ran into issues with projections (i.e. UTM not being handled by default in OL). So after installing proj4 and registering the corresponding projection, it requested the file, but then Chrome crashed a number of time.

This leads me to the conclusion that this has quite a bit of small pitfalls when implemented for "all kinds of" results and thus needs proper support from back-ends, incl. CORS and good STAC metadata (e.g. including projection as WKT, no-data value, default visualization(?), bands, ...)

Next attempt: stacLayer, which is currently in development for Leaflet.

**Comment by jdries** [comment]
Nice experiment!
Note that I would indeed expect problems with reprojection. I would propose to go for the GEE solution there, and simply only support this if data is generated in web mercator. (GEE does this by default, in openEO, the user will have to reproject more explicitly.) If that would make things work, (in leaflet or OL), we would have a nice demo of what is possible with current open source options.

**Comment by m-mohr** [comment]
Reprojection doesn't seem to be a too big problem, depending on which library you use. For many projections, it works out-of-the-box in the Leaflet implementation. I've experimented with the stacLayer plugin a bit in the last few days (for STAC Browser) and several projections worked flawlessly in my tests. So this seems more like an OpenLayers issue right now, which one could probably solve, but let's get them to a more mature state first. If work continues in such a good way for stacLayer/Leaflet, I have enough reasoning to switch back to Leaflet in the Web Editor and then we can give it another try. Let's see... (and there's always still the option to set up a tile server, too).
