### ISSUE TITLE
Support touch events

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-web-editor#45]
Currently, some parts can only be used with a mouse. For example, the splitters or the visual builder. Implement touch events so that users can use the web editor on mobile devices better.

**Comment by m-mohr** [comment]
Something like this might help: https://stackoverflow.com/questions/1517924/javascript-mapping-touch-events-to-mouse-events

**Comment by christophfriedrich** [comment]
The map splitter works okay with my Windows 10 laptop's touchscreen.

**Comment by m-mohr** [comment]
Can't implement, touch device is missing at work. Can't/Won't fix until I have a device to test it with.

**Comment by clausmichele** [comment]
I have a windows 10 laptop with touch screen, if you need help with testing.

**Comment by m-mohr** [comment]
@clausmichele Thank you, but for development you'll certainly want to also be able to debug on a touch device. Otherwise, it will get pretty annoying to fix issues. Also, this is low priority right now.
