### ISSUE TITLE
Bottom of scroll areas is not shown on screens with small height

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-web-editor#47]
When the viewport is not high enough, the list of (e.g.) web services adds a scroll bar - but the bottom (ca.) fourth is not displayed.

Example:

![image](https://user-images.githubusercontent.com/17781682/64254705-3f55c700-cf20-11e9-88b6-d0582e5fa208.png)

**Comment by m-mohr** [comment]
Thanks, should be fixed.
