### ISSUE TITLE
View on Map -> Scroll to extent

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-web-editor#49]
If a service works on a limited extent, try to scroll to the extent.

**Comment by christophfriedrich** [comment]
That would be extremely helpful -- I just wondered "why is nothing being displayed" when trying out the Australia example 🤦‍♂

**Comment by m-mohr** [comment]
As far as I remember @slim01 worked on this, but didn't find a way to solve it.

**Comment by m-mohr** [comment]
For XYZ, the issue is that there's no way to reliably figure out the extent. It just loads transparent tiles for areas without data. 
For other data, we may be able to zoom, but the map doesn't support other data yet.

**Comment by christophfriedrich** [comment]
Would it be possible to retrieve the necessary extent information from the process graph the service is based on?

**Comment by m-mohr** [comment]
No, that's not very reliable unfortunately.

**Comment by m-mohr** [comment]
We can likely use the STAC metadata in the future.
