### ISSUE TITLE
Edge issues

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-web-editor#50]
Microsoft Edge 41.16299.371.0
Microsoft EdgeHTML 16.16299

- [x] URLSearchParams is not defined

- [x] When trying to drag-and-drop the S2 collection into the Model Builder pane:
{description: "Element nicht gefunden. ", message: "Element nicht gefunden. ", number: -2147023728, stack: "Error: Element nicht gefunden. at h.methods.onDrag (http://editor.openeo.org/js/chunk-78bca8e4.91d6b7bf.js:7:105707) at on.dragstart (http://editor.openeo.org/js/chunk-78bca8e4.91d6b7bf.js:7:102572) at ne (http://editor.openeo.org/js/chunk-vendors~fdc6512a.013ee82b.js:7:11638) at n (http://editor.openeo.org/js/chunk-vendors~fdc6512a.013ee82b.js:7:13449) at o._wrapper (http://editor.openeo.org/js/chunk-vendors~fdc6512a.013ee82b.js:7:51703)"}
Adding via the + button works

- [x] Drawing an arrow between S2 collection and a filter_bbox process works too, but loading a process graph from a service or job doesn't paint all edges.

Added by @christophfriedrich :

- [x] When loading the NO2 process graph from a stored web service, some of the arrows are missing:
![grafik](https://user-images.githubusercontent.com/17781682/64334642-3d9c0a00-cfd9-11e9-8c1f-0ebb7fe19beb.png)

- [ ] Zooming in the Model Builder doesn't work with a touchpad: neither the standard scroll gesture (going up and down with two fingers) nor [pinching](http://hammerjs.github.io/recognizer-pinch/) (the latter zooms the entire page). On Firefox both work as one would expect. (Scrolling with a real mouse wheel works though.)

**Comment by christophfriedrich** [comment]
- When loading the NO2 process graph from a stored web service, some of the arrows are missing:
![grafik](https://user-images.githubusercontent.com/17781682/64334642-3d9c0a00-cfd9-11e9-8c1f-0ebb7fe19beb.png)

- Zooming in the Model Builder doesn't work with a touchpad: neither the standard scroll gesture (going up and down with two fingers) nor [pinching](http://hammerjs.github.io/recognizer-pinch/) (the latter zooms the entire page). On Firefox both work as one would expect. (Scrolling with a real mouse wheel works though.)

**Comment by christophfriedrich** [comment]
During my live demo at the 52N conference (I accidentally used Edge for this), loading a process graph from a web service didn't work, but I didn't remember the error message nor was I able to reproduce it so far. It may have had something to do with an incomplete process graph being already present in the Model Builder. Let's not worry about it until it happens again somewhere.

**Comment by m-mohr** [comment]
> * URLSearchParams

Is available since EdgeHTML 17, therefore we'll not fix it.

**Comment by m-mohr** [comment]
Will work with upcoming Edge based on the Chrome Engine. Closing.

**Comment by christophfriedrich** [comment]
Nice when issues fix themselves :D
