### ISSUE TITLE
Show callbacks in main model

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-web-editor#51]
Would it be possible to render the "sub process graphs" (e.g. the callback in the EVI example) in the main model too? This would make it more "graph-y".

**Comment by m-mohr** [comment]
Unfortunately that is very complex to do and will probably not happen anytime soon.

**Comment by m-mohr** [comment]
This is not likely to be implemented:
1. It makes the graph view very complex
2. The sub-graphs belong to a parameter with multiple parameters passed and thus it's not easy to visualize. 
3. They don't really belong together, the graphs are mostly Independent graphs.
