### ISSUE TITLE
Saving bands array without content produces error the next time it's opened

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-web-editor#54]
Steps to reproduce:

1. add new collection to visual builder
2. double click to open options
3. go to bands
4. select "array"
5. click "add"
6. realise you don't know what to type there
7. click "save"
8. open information window
9. find what you're looking for
10. close information window
11. double click to open options
12. go to bands
13. see that "null" is selected again (although it was saved differently?!)
14. select "array" again
15. see errors:

> fatal error: t is null

and 

> fatal error: e[i] is null

**Comment by m-mohr** [comment]
Yes, I had a similar error. When you insert two elements (e.g. B4, B8) and have one empty element, your in a loop of errors which you can't really recover from.

**Comment by m-mohr** [comment]
Fixed.
