### ISSUE TITLE
Convert band math formulas into process graphs?

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-web-editor#64]
The Python Client has a nice way to translate native maths expressions into process graphs. We should check whether we could introduce something as well.

**Comment by slim01** [comment]
To parse the math expressions [tapdigit](https://github.com/ariya/tapdigit) seems to be a lightweight alternative to extensive libraries like math.js, although it is quite old and not much used.

**Comment by m-mohr** [comment]
Is available now. I'm now implementing the other way round: Process Graph to Formula.
