### ISSUE TITLE
Text when no collection/process/process graph matches the search term

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-web-editor#65]
When the user enters a search term and none of the collections, processes, or process graphs at the Hub matches it, the texts that are displayed are: "No collections available", "No processes available", "No compatible process graphs available at the openEO Hub" respectively.

IMO these texts are not accurate, because there *are* items "available", it's just that none of them matched the current search term.

Therefore the texts should be changed to e.g. "No matched collections", "No matched processes", "No matched compatible process graphs at the openEO Hub".

**Comment by m-mohr** [comment]
This is correct, I think I'll change it to "No ... found".

**Comment by m-mohr** [comment]
Fixed in #68.
