### ISSUE TITLE
Bug when connecting multiple boxes with save_result box

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-web-editor#66]
Steps to reproduce:

- Open web editor, log into GEE driver
- Add collection "AU/GA/AUSTRALIA_5M_DEM" via drag and drop
- Add save_result process via drag and drop
- Connect them (drag an arrow from the collection's Result to save_result's data input)
- Realise that you need a linear_scale_range
- Add apply process via drag and drop
- From apply's data input drag an arrow to the collection's Output
- From apply's Output drag an arrow to save_result's data input
- Note error message in toast: "Can't determine which object property this input should be assigned to. Please specify manually in Process Graph mode."
- Note that the arrow is created anyway
- Go into Process Graph mode
- Note that in the created process graph, save_result still receives from the collection directly; the newly created arrow isn't modelled
- Go back to Visual Model mode
- See that both arrows are still being rendered
- Delete the connection between the collection and save_result
- Note that this is now a process graph that should be able to run (except the missing callback for the apply, but that's not the point here)
- Hit the play button
- Note error message: "Process 'save_result' requires argument 'data'."

**Comment by m-mohr** [comment]
> - Note error message in toast: "Can't determine which object property this input should be assigned to. Please specify manually in Process Graph mode."

You are adding two inputs to save_result and the process can't decide which input to use (or how to merge two inputs). Therefore there's the message, although it is "a bit" counter-intuitive (but I can't guess generally what the user want's to do). You should better have removed the connection from load_collection to save_result before adding more connections.

> - Note that the arrow is created anyway
> - Go into Process Graph mode
> - Note that in the created process graph, `save_result` still receives from the collection directly; the newly created arrow isn't modelled

That's the actual issue, but the Web Editor just doesn't know what should be done. So maybe I need to reject adding an connection...

> - Go back to Visual Model mode
> - See that *both* arrows are still being rendered

You haven't changed anything in JSON/PG mode, therefore it doesn't re-render the graph and it stays as it is.

> - Note that this is now a process graph that should be able to run (except the missing callback for the `apply`, but that's not the point here)
> - Hit the play button
> - Note error message: "Process 'save_result' requires argument 'data'."

It hasn't added the connection between the apply and save_result due to the message above and you haven't fixed it in JSON/PG mode as requested by the editor.

**Comment by christophfriedrich** [comment]
I know that it was wrong what I did, yet that's what I did intuitively (thinking that I can remove the old arrow later) *and the Web Editor let me do it*.

> Note that the arrow is created anyway

That's the error, this shouldn't happen. Like you said: "maybe I need to reject adding an connection..." The error message should be something like "Cannot take more than one input -- remove existing input to connect a new one".

>> See that both arrows are still being rendered
> You haven't changed anything in JSON/PG mode, therefore it doesn't re-render the graph and it stays as it is.

I would have expected that the graph is re-rendered every time you switch back from JSON/PG mode, i.e. in this case I would expect that my wrong drawing is discarded and replaced with what's currently modelled by the JSON.

> It hasn't added the connection between the apply and save_result due to the message above and you haven't fixed it in JSON/PG mode as requested by the editor.

But I fixed it in the graph mode, haven't I? At least what is being rendered *looks* legit, so I would expect it to work.

**Comment by m-mohr** [comment]
> That's the error, this shouldn't happen. Like you said: "maybe I need to reject adding an connection..." The error message should be something like "Cannot take more than one input -- remove existing input to connect a new one".

Unfortunately, I don't really know whether the input can take more than one input or not. 


> I would have expected that the graph is re-rendered every time you switch back from JSON/PG mode, i.e. in this case I would expect that my wrong drawing is discarded and replaced with what's currently modelled by the JSON.

Just changing the view shouldn't change any data. Also, it would discard the current placement of the nodes. Therefore it doesn't re-render if nothing has changed.


> But I fixed it in the graph mode, haven't I? At least what is being rendered *looks* legit, so I would expect it to work.

And that's what we can actually solve, I hope.

**Comment by slim01** [comment]
You will now get an error message and the arrow will not be drawn.
