### ISSUE TITLE
filter_polygon process building in Visual model has issue probably

### ISSUE THREAD

**Issue by prateekbudhwar** [Open-EO/openeo-web-editor#71]
When creating a polygon using type as "Polygon" the coordinates field is declared as JSONArray twice, while i think it should be only once, currently its as shown below,

```json
"3": {
    "process_id": "filter_polygon",
    "arguments": {
      "polygons": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              15.254881381988527,
              21.453068633086772
            ],
            [
              13.057615756988529,
              19.72534224805787
            ],
            [
              15.78222513198853,
              16.467694748288963
            ],
            [
              19.56152200698853,
              17.97873309555618
            ],
            [
              15.254881381988527,
              21.453068633086772
            ]
          ]
        ]
      }
    }
  }
```

**Comment by m-mohr** [comment]
Hi @prateekbudhwar,

could you use code tags and/or a JSON formatter so that the code is easier to read, please?

The polygons parameter is GeoJSON. Is the example valid GeoJSON?

**Comment by prateekbudhwar** [comment]
Hi @m-mohr 

As I mentioned in the issue topic the graph is generated using the Visual model, not by me, so please check the web editor visual model to build the filter_polygon process to regenerate the above JSON process

**Comment by m-mohr** [comment]
@prateekbudhwar The GeoJSON is valid according to http://geojsonlint.com/ so I'm not sure what I should change.
