### ISSUE TITLE
OIDC authentication: pop up blocker

### ISSUE THREAD

**Issue by bgoesswe** [Open-EO/openeo-web-editor#81]
When trying to connect via OIDC I always got "Sorry, credentials are wrong" as an error message. I found out (after installing it locally and commenting out the catching of the Exception) that the issue was that my browser blocked the popup window.
I think it would be nice to eighter add this in the error message as a possible cause, or check for popup blocker to have a concrete error message.

**Comment by m-mohr** [comment]
It now shows for OIDC whatever the browser / OIDC library throws. For me it was "Popup window closed", but it's likely that will be different depending on the browser config. Not a very intuitive message, but better than before.
