### ISSUE TITLE
[Feature request] Display newest job first in batch jobs

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-web-editor#87]
It would be nice to have the batch jobs list inverted, showing at the top the latest added job.
With a long list of jobs, every time you add a job you need to scroll down to the bottom to interact with it.

**Comment by m-mohr** [comment]
I'm planning to implement table sorting soon. :-)

**Comment by m-mohr** [comment]
Has been implemented: 

![image](https://user-images.githubusercontent.com/8262166/84688081-02067700-af3f-11ea-8866-0c9769f86666.png)
