### ISSUE TITLE
load_collection does not show selected bands

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-web-editor#91]
In version 0.5.0-beta.1 , using load_collecton:
1. select the bands
2. save
3. reopen load_collection properties
4. the previously selected bands do not show up

Bug not present in version 0.4.1

**Comment by m-mohr** [comment]
Thanks for reporting this issue. It was a bit difficult to fix, but should be working now. Will be deployed in the next days.

**Comment by m-mohr** [comment]
Must re-open, there's still another issue I'm now fixing.

**Comment by clausmichele** [comment]
There is the same issue with the bounding-box:
if a bbox is already selected and I reopen the load_collection properties it doesn't show it.

**Comment by m-mohr** [comment]
I think I fixed most issues related to the parameter editing. I deployed a new version. Does it work for you?

**Comment by clausmichele** [comment]
Yes, it's solved!
