### ISSUE TITLE
reduce_dimension and apply doesn't show the "data" block immediately

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-web-editor#92]
In order to see the data block inside the reduce_dimension block now the procedure is the following:
1. add a reduce_dimension block and connect the input to some data
2. open it, add a reduce process and save
3. open it again and connect the data block that now is visible to the chosen process

It would be nice to show up the data and context blocks as soon as there is some data connected as input to the reduce_dimension process, avoiding the point 3. Same for the apply process, maybe also others.

**Comment by m-mohr** [comment]
I think that has been fixed yesterday, just hadn't deployed yet. I just redeployed the Web Editor. Could you check it's working now?

**Comment by clausmichele** [comment]
Yes, it's fixed now.
