### ISSUE TITLE
save_result does not show options

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-web-editor#93]
The save_result process does not show options for any format chosen, e.g. for PNG it is not possible to choose the corresponding bands.

**Comment by m-mohr** [comment]
Hehe, you are finding all the issues at the moment I'm working on, great :-) I have a fix nearly ready.

**Comment by m-mohr** [comment]
I think I fixed most issues related to the parameter editing. I deployed a new version. Does it work for you?
