### ISSUE TITLE
FileFormatEditor doesn't always save selected values

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-web-editor#96]
> save_result does not allow Null for "The size for the longest side the image, in pixels"

This option can be set to Null, which I understand as "original size" without resampling. However, if it's set to Null it does not store the setting and goes back to the integer value.

**Comment by clausmichele** [comment]
Additionally, the default value for epsg is not shown in the json unless modified and saved, shouldn't it be Null by default? The default value should be no reprojection/keep the one of the data in my opinion.

**Comment by m-mohr** [comment]
Just fixed it in dev, will deploy it now. Could you check if it works for you, please?

As I think this is about the GEE driver(?), setting the "The size for the longest side the image, in pixels" setting to null doesn't necessarily mean original size. GEE limits the export size anyway so (I can't remember from my head) either the default or the maximum value given for the parameter.

**Comment by clausmichele** [comment]
The default epsg 3857 is not shown in the process graph, is it intended to be like this or not?

**Comment by m-mohr** [comment]
Yes, default values are usually omitted.
